### PR TITLE
Allow defining a plugin getter.

### PR DESCRIPTION
**Pull request by fatfisz**
This is connected to #14.

### CODE REVIEW

**Comment by lukeapage** [comment]
Good spot of the issue, thanks for the fix.

Please could you add info to the readme about this new way of specifying plugins and perhaps when you would use it (e.g. babel with helpers plugin)

**Comment by lukeapage** [comment]
@chrisprice I'll give you time to respond before merging, let me know if it looks good and am happy for me to merge when ready

**Comment by fatfisz** [comment]
Yes, of course. I can't do it right now, but expect an update in an hour or so.

**Comment by fatfisz** [comment]
@lukeapage I've added some info to the README file, is the wording ok?

**Comment by chrisprice** [comment]
:+1: LGTM, thanks guys!

**Comment by lukeapage** [comment]
published as 0.7.0

**Pull request merged**
