### PR TITLE
Make rollup update through minor versions even while in pre-release

### PR DESCRIPTION
**Pull request by lukeapage**
as per https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4

### CODE REVIEW

**Comment by lukeapage** [comment]
damn the tests will fail again because 0.17 of rollup is a rollback

**Comment by chrisprice** [comment]
Yea that's what I was afraid of. Have there not been breaking changes in
the patch versions so far?

**Comment by lukeapage** [comment]
yes - I had to fix tests between 0.16.2 and 0.16.3

what rollup does for tests is it runs the output and has asserts in the output to check it compiles.. could be an option for this package?

**Comment by lukeapage** [comment]
> could be an option for this package?

though not for testing sourcemaps.

**Comment by lukeapage** [comment]
I fixed the tests again, they will probably change again when 0.18 is released, then hopefully be more stable after that...

**Comment by chrisprice** [comment]
Thanks

**Pull request merged**
