### PR TITLE
Bring options up-to-date

### LINKED ISSUE #52: Missing options
Some current options like chunkFileNames are missing,
I'll create a pullrequest for this one

### PR DESCRIPTION
**Pull request by scythianfuego**
#### Information
Fixes #52

#### Description
Options added.

#### PR checklist

If you've made change to the code, be sure to validate this checklist:

 - [x] I have read the [contribution guideline](../contributing.md)
 - [x] I have minimized linting error when running `npm run lint`
 - [ ] I have added tests for my code
 - [x] I have successfully ran tests with `npm test`
 - [x] I am an awesome human being

"With plugin array" test is currently broken, didn't fix one.

### CODE REVIEW

**Comment by GMartigny** [comment]
Hi and thanks for the PR. Could you provide the source from where you got all the options? So it could be referenced later.
Thanks again

**Comment by scythianfuego** [comment]
Current documentation is more or less adequate
https://rollupjs.org/guide/en/#rolluprollup
**inputOptions object** and **outputOptions object**

It seems that it is slightly older than the code itself, there is a list in typescript definitions
https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts#L425
(there is something like importMetaUrl mentioned there which is not in the documentation)

I didn't include experimental ones as well.

**Comment by GMartigny** [comment]
I reverted your "fix tests" commit because not in the scope of this PR. Although, you're right these tests sometimes fail because the race condition can change.

Thanks a lot for the fix, I'll push a new version following this.

**Comment by GMartigny** [comment]
I forgot, is it ok with you if I add you to the contributors list ?

**Comment by scythianfuego** [comment]
up to you, I don't mind either

> I forgot, is it ok with you if I add you to the contributors list ?

**Comment by GMartigny** [comment]
Done 😉

**Pull request merged**
