### PR TITLE
Support rollup 0.45.0

### PR DESCRIPTION
**Pull request by steindani**
bundle.generate(...) now returns a Promise

### CODE REVIEW

**Comment by seanmclucas** [comment]
@steindani It would probably be a good idea to start fixing the version in package.json to prevent the library from breaking in the future:

https://github.com/rollup/rollup/issues/1485

**Comment by alippai** [comment]
As long as they don't release the version 1.0.0 this seems to be our best shot. Keeping grunt-rollup up-to-date day by day and releasing patches ASAP.

**Comment by steindani** [comment]
@seanmclucas You are right, thanks!

**Comment by seanmclucas** [comment]
@chrisprice Any objection to merging and releasing this? At the moment, the latest version of grunt-rollup is broken.

**Pull request merged**
